var figure = {
    "frames": [], 
    "layout": {
        "breakpoints": [], 
        "geo": {
            "oceancolor": "rgb(0,255,255)", 
            "projection": {
                "rotation": {
                    "lon": 7.229405394027622
                }, 
                "scale": 0.9138314502294014, 
                "type": "Mercator"
            }, 
            "center": {
                "lat": -13.69091051667787, 
                "lon": 7.229405394027622
            }, 
            "showocean": true, 
            "showframe": true
        }, 
        "title": "Terrorist Activities By Country"
    }, 
    "data": [
        {
            "colorbar": {
                "tickprefix": "", 
                "autotick": true, 
                "title": "Activities"
            }, 
            "locationssrc": "wiput1999:0:d9ed6e", 
            "zmax": 22130, 
            "uid": "3a6ead", 
            "colorscale": [
                [
                    0, 
                    "#440154"
                ], 
                [
                    0.06274509803921569, 
                    "#48186a"
                ], 
                [
                    0.12549019607843137, 
                    "#472d7b"
                ], 
                [
                    0.18823529411764706, 
                    "#424086"
                ], 
                [
                    0.25098039215686274, 
                    "#3b528b"
                ], 
                [
                    0.3137254901960784, 
                    "#33638d"
                ], 
                [
                    0.3764705882352941, 
                    "#2c728e"
                ], 
                [
                    0.4392156862745098, 
                    "#26828e"
                ], 
                [
                    0.5019607843137255, 
                    "#21918c"
                ], 
                [
                    0.5647058823529412, 
                    "#1fa088"
                ], 
                [
                    0.6274509803921569, 
                    "#28ae80"
                ], 
                [
                    0.6901960784313725, 
                    "#3fbc73"
                ], 
                [
                    0.7529411764705882, 
                    "#5ec962"
                ], 
                [
                    0.8156862745098039, 
                    "#84d44b"
                ], 
                [
                    0.8784313725490196, 
                    "#addc30"
                ], 
                [
                    0.9411764705882353, 
                    "#d8e219"
                ], 
                [
                    1, 
                    "#fde725"
                ]
            ], 
            "zsrc": "wiput1999:0:dd821f", 
            "text": [
                "Afghanistan", 
                "Albania", 
                "Algeria", 
                "Andorra", 
                "Angola", 
                "Antigua and Barbuda", 
                "Argentina", 
                "Armenia", 
                "Australia", 
                "Austria", 
                "Azerbaijan", 
                "Bahamas", 
                "Bahrain", 
                "Bangladesh", 
                "Barbados", 
                "Belarus", 
                "Belgium", 
                "Belize", 
                "Benin", 
                "Bhutan", 
                "Bolivia", 
                "Bosnia-Herzegovina", 
                "Botswana", 
                "Brazil", 
                "Brunei", 
                "Bulgaria", 
                "Burkina Faso", 
                "Burundi", 
                "Cambodia", 
                "Cameroon", 
                "Canada", 
                "Central African Republic", 
                "Chad", 
                "Chile", 
                "China", 
                "Colombia", 
                "Comoros", 
                "Costa Rica", 
                "Croatia", 
                "Cuba", 
                "Cyprus", 
                "Czech Republic", 
                "Czechoslovakia", 
                "Democratic Republic of the Congo", 
                "Denmark", 
                "Djibouti", 
                "Dominica", 
                "Dominican Republic", 
                "East Germany (GDR)", 
                "East Timor", 
                "Ecuador", 
                "Egypt", 
                "El Salvador", 
                "Equatorial Guinea", 
                "Eritrea", 
                "Estonia", 
                "Ethiopia", 
                "Falkland Islands", 
                "Fiji", 
                "Finland", 
                "France", 
                "French Guiana", 
                "French Polynesia", 
                "Gabon", 
                "Gambia", 
                "Georgia", 
                "Germany", 
                "Ghana", 
                "Greece", 
                "Grenada", 
                "Guadeloupe", 
                "Guatemala", 
                "Guinea", 
                "Guinea-Bissau", 
                "Guyana", 
                "Haiti", 
                "Honduras", 
                "Hong Kong", 
                "Hungary", 
                "Iceland", 
                "India", 
                "Indonesia", 
                "International", 
                "Iran", 
                "Iraq", 
                "Ireland", 
                "Israel", 
                "Italy", 
                "Ivory Coast", 
                "Jamaica", 
                "Japan", 
                "Jordan", 
                "Kazakhstan", 
                "Kenya", 
                "Kosovo", 
                "Kuwait", 
                "Kyrgyzstan", 
                "Laos", 
                "Latvia", 
                "Lebanon", 
                "Lesotho", 
                "Liberia", 
                "Libya", 
                "Lithuania", 
                "Luxembourg", 
                "Macau", 
                "Macedonia", 
                "Madagascar", 
                "Malawi", 
                "Malaysia", 
                "Maldives", 
                "Mali", 
                "Malta", 
                "Martinique", 
                "Mauritania", 
                "Mauritius", 
                "Mexico", 
                "Moldova", 
                "Montenegro", 
                "Morocco", 
                "Mozambique", 
                "Myanmar", 
                "Namibia", 
                "Nepal", 
                "Netherlands", 
                "New Caledonia", 
                "New Hebrides", 
                "New Zealand", 
                "Nicaragua", 
                "Niger", 
                "Nigeria", 
                "North Korea", 
                "North Yemen", 
                "Norway", 
                "Pakistan", 
                "Panama", 
                "Papua New Guinea", 
                "Paraguay", 
                "People's Republic of the Congo", 
                "Peru", 
                "Philippines", 
                "Poland", 
                "Portugal", 
                "Qatar", 
                "Republic of the Congo", 
                "Rhodesia", 
                "Romania", 
                "Russia", 
                "Rwanda", 
                "Saudi Arabia", 
                "Senegal", 
                "Serbia", 
                "Serbia-Montenegro", 
                "Seychelles", 
                "Sierra Leone", 
                "Singapore", 
                "Slovak Republic", 
                "Slovenia", 
                "Solomon Islands", 
                "Somalia", 
                "South Africa", 
                "South Korea", 
                "South Sudan", 
                "South Vietnam", 
                "South Yemen", 
                "Soviet Union", 
                "Spain", 
                "Sri Lanka", 
                "St. Kitts and Nevis", 
                "St. Lucia", 
                "Sudan", 
                "Suriname", 
                "Swaziland", 
                "Sweden", 
                "Switzerland", 
                "Syria", 
                "Taiwan", 
                "Tajikistan", 
                "Tanzania", 
                "Thailand", 
                "Togo", 
                "Trinidad and Tobago", 
                "Tunisia", 
                "Turkey", 
                "Turkmenistan", 
                "Uganda", 
                "Ukraine", 
                "United Arab Emirates", 
                "United Kingdom", 
                "United States", 
                "Uruguay", 
                "Uzbekistan", 
                "Vanuatu", 
                "Vatican City", 
                "Venezuela", 
                "Vietnam", 
                "Wallis and Futuna", 
                "West Bank and Gaza Strip", 
                "West Germany (FRG)", 
                "Western Sahara", 
                "Yemen", 
                "Yugoslavia", 
                "Zaire", 
                "Zambia", 
                "Zimbabwe"
            ], 
            "zmin": 1, 
            "locations": [
                "AFG", 
                "ALB", 
                "DZA", 
                "AND", 
                "AGO", 
                "ATG", 
                "ARG", 
                "ARM", 
                "AUS", 
                "AUT", 
                "AZE", 
                null, 
                "BHR", 
                "BGD", 
                "BRB", 
                "BLR", 
                "BEL", 
                "BLZ", 
                "BEN", 
                "BTN", 
                "BOL", 
                null, 
                "BWA", 
                "BRA", 
                "BRN", 
                "BGR", 
                "BFA", 
                "BDI", 
                "KHM", 
                "CMR", 
                "CAN", 
                "CAF", 
                "TCD", 
                "CHL", 
                "CHN", 
                "COL", 
                "COM", 
                "CRI", 
                "HRV", 
                "CUB", 
                "CYP", 
                "CZE", 
                null, 
                null, 
                "DNK", 
                "DJI", 
                "DMA", 
                "DOM", 
                null, 
                null, 
                "ECU", 
                "EGY", 
                "SLV", 
                "GNQ", 
                "ERI", 
                "EST", 
                "ETH", 
                null, 
                "FJI", 
                "FIN", 
                "FRA", 
                null, 
                "PYF", 
                "GAB", 
                null, 
                "GEO", 
                "DEU", 
                "GHA", 
                "GRC", 
                "GRD", 
                null, 
                "GTM", 
                "GIN", 
                "GNB", 
                "GUY", 
                "HTI", 
                "HND", 
                "HKG", 
                "HUN", 
                "ISL", 
                "IND", 
                "IDN", 
                null, 
                "IRN", 
                "IRQ", 
                "IRL", 
                "ISR", 
                "ITA", 
                null, 
                "JAM", 
                "JPN", 
                "JOR", 
                "KAZ", 
                "KEN", 
                "KSV", 
                "KWT", 
                "KGZ", 
                "LAO", 
                "LVA", 
                "LBN", 
                "LSO", 
                "LBR", 
                "LBY", 
                "LTU", 
                "LUX", 
                "MAC", 
                "MKD", 
                "MDG", 
                "MWI", 
                "MYS", 
                "MDV", 
                "MLI", 
                "MLT", 
                null, 
                "MRT", 
                "MUS", 
                "MEX", 
                "MDA", 
                "MNE", 
                "MAR", 
                "MOZ", 
                null, 
                "NAM", 
                "NPL", 
                "NLD", 
                "NCL", 
                null, 
                "NZL", 
                "NIC", 
                "NER", 
                "NGA", 
                null, 
                null, 
                "NOR", 
                "PAK", 
                "PAN", 
                "PNG", 
                "PRY", 
                null, 
                "PER", 
                "PHL", 
                "POL", 
                "PRT", 
                "QAT", 
                null, 
                null, 
                "ROU", 
                "RUS", 
                "RWA", 
                "SAU", 
                "SEN", 
                "SRB", 
                null, 
                "SYC", 
                "SLE", 
                "SGP", 
                null, 
                "SVN", 
                "SLB", 
                "SOM", 
                "ZAF", 
                null, 
                "SSD", 
                null, 
                null, 
                null, 
                "ESP", 
                "LKA", 
                null, 
                null, 
                "SDN", 
                "SUR", 
                "SWZ", 
                "SWE", 
                "CHE", 
                "SYR", 
                "TWN", 
                "TJK", 
                "TZA", 
                "THA", 
                "TGO", 
                "TTO", 
                "TUN", 
                "TUR", 
                "TKM", 
                "UGA", 
                "UKR", 
                "ARE", 
                "GBR", 
                "USA", 
                "URY", 
                "UZB", 
                "VUT", 
                null, 
                "VEN", 
                "VNM", 
                null, 
                null, 
                null, 
                null, 
                "YEM", 
                null, 
                null, 
                "ZMB", 
                "ZWE"
            ], 
            "textsrc": "wiput1999:0:62a836", 
            "autocolorscale": false, 
            "reversescale": true, 
            "showscale": true, 
            "type": "choropleth", 
            "marker": {
                "line": {
                    "color": "rgb(200,200,200)", 
                    "width": 0.5
                }
            }, 
            "z": [
                11306, 
                79, 
                2729, 
                1, 
                493, 
                1, 
                806, 
                24, 
                104, 
                109, 
                47, 
                5, 
                186, 
                1605, 
                3, 
                13, 
                148, 
                8, 
                8, 
                6, 
                314, 
                159, 
                10, 
                268, 
                1, 
                52, 
                20, 
                587, 
                258, 
                234, 
                84, 
                235, 
                85, 
                2351, 
                247, 
                8163, 
                5, 
                67, 
                57, 
                30, 
                132, 
                29, 
                10, 
                628, 
                41, 
                21, 
                3, 
                89, 
                38, 
                10, 
                217, 
                2165, 
                5320, 
                2, 
                10, 
                16, 
                163, 
                1, 
                17, 
                18, 
                2642, 
                7, 
                3, 
                4, 
                3, 
                216, 
                703, 
                19, 
                1231, 
                5, 
                56, 
                2050, 
                25, 
                9, 
                26, 
                213, 
                322, 
                26, 
                46, 
                4, 
                10978, 
                735, 
                1, 
                676, 
                22130, 
                290, 
                2133, 
                1556, 
                61, 
                34, 
                401, 
                101, 
                27, 
                582, 
                188, 
                76, 
                32, 
                26, 
                16, 
                2454, 
                29, 
                33, 
                2053, 
                8, 
                16, 
                33, 
                117, 
                27, 
                4, 
                95, 
                18, 
                417, 
                20, 
                12, 
                18, 
                2, 
                504, 
                21, 
                5, 
                36, 
                351, 
                430, 
                151, 
                967, 
                128, 
                31, 
                1, 
                20, 
                1970, 
                139, 
                3418, 
                1, 
                6, 
                18, 
                13634, 
                127, 
                81, 
                104, 
                3, 
                6088, 
                6212, 
                36, 
                139, 
                7, 
                34, 
                83, 
                6, 
                2158, 
                157, 
                317, 
                118, 
                11, 
                11, 
                2, 
                98, 
                7, 
                18, 
                6, 
                4, 
                3482, 
                1987, 
                38, 
                171, 
                1, 
                2, 
                78, 
                3245, 
                2981, 
                2, 
                1, 
                861, 
                66, 
                16, 
                118, 
                108, 
                1949, 
                48, 
                185, 
                53, 
                3668, 
                48, 
                22, 
                104, 
                4106, 
                2, 
                381, 
                1650, 
                22, 
                5098, 
                2758, 
                76, 
                21, 
                2, 
                1, 
                275, 
                10, 
                1, 
                2144, 
                541, 
                5, 
                3109, 
                203, 
                48, 
                60, 
                98
            ], 
            "locationmode": "Code", 
            "zauto": true
        }
    ]
}